### ISSUE TITLE
if this a bug in your corpus build?

### ISSUE THREAD

**Issue by marcusau** [jidasheng/bi-lstm-crf#3]
example: 

in my dataset.txt , the first row is : 
作者根據和比利案件有關的醫院人員、律師、警員提供的第一手資料，和比利偷偷寫下的內心筆記，揭露了醫院內對待精神病人的黑幕，和比利既要面對人格融合，及醫院內精神及肉體的不人道對待的矛盾。	["B","E","B","E","S","B","E","B","E","B","E","S","B","E","B","E","S","B","E","S","B","E","B","E","S","B","M","M","M","E","S","S","B","E","B","E","B","E","S","B","E","B","E","S","B","E","S","B","E","S","B","E","B","M","M","E","S","B","E","S","S","B","E","B","E","B","E","B","E","B","E","S","S","B","E","S","B","E","S","B","E","S","B","M","E","B","E","S","B","E","S"]

the first part (sentence) is string
the second part  (BMES label )  is list

    config ./data/vocab.json loaded
    config ./data/tags.json loaded
    tag dict file => ./model/tags.json
    tag dict file => ./model/vocab.json
    parsing ./data/dataset.txt: 37271it [00:01, 29734.05it/s]
    Traceback (most recent call last):
      File "/Users/marcusau/jidasheng/lib/python3.6/site-              packages/bi_lstm_crf/app/preprocessing/preprocess.py", line 123, in __build_corpus
          sentence = json.loads(sentence)
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
          return _default_decoder.decode(s)
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
          raise JSONDecodeError("Expecting value", s, err.value) from None
      json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
          "__main__", mod_spec)
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
          exec(code, run_globals)
        File "/Users/marcusau/jidasheng/lib/python3.6/site-packages/bi_lstm_crf/__main__.py", line 3, in <module>
          main()
        File "/Users/marcusau/jidasheng/lib/python3.6/site-packages/bi_lstm_crf/app/train.py", line 119, in main
          train(args)
        File "/Users/marcusau/jidasheng/lib/python3.6/site-packages/bi_lstm_crf/app/train.py", line 46, in train
          args.corpus_dir, args.val_split, args.test_split, max_seq_len=args.max_seq_len)
        File "/Users/marcusau/jidasheng/lib/python3.6/site-packages/bi_lstm_crf/app/preprocessing/preprocess.py", line 69, in load_dataset
          xs, ys = self.__build_corpus(corpus_dir, max_seq_len)
        File "/Users/marcusau/jidasheng/lib/python3.6/site-packages/bi_lstm_crf/app/preprocessing/preprocess.py", line 131, in __build_corpus
          raise ValueError("exception raised when parsing line {}\n {}".format(idx + 1, e))
      ValueError: exception raised when parsing line 37514
       Expecting value: line 1 column 2 (char 1)

**Comment by marcusau** [comment]
or could you disclose the code about how to convert a tokenised text file into the format of dataset.txt?

thanks a lot

I can convert tags.json and vocab.json on my own. and they work well

**Comment by marcusau** [comment]
<img width="1417" alt="Screenshot 2019-12-06 at 12 52 35 AM" src="https://user-images.githubusercontent.com/31444195/70256052-c0905480-17c2-11ea-961c-f791d2a63e26.png">
this is a sample of my dataset.txt file.
I think the format is compatible to your requirement, right??

please point out if i make a mistake

**Comment by jidasheng** [comment]
The log show the error occurred when parsing line 37514 in dataset.txt. 
Open and take a look.

**Comment by marcusau** [comment]
on it .. 
Thanks ,. i will refine my corpus tonight.  :)
